title: "Go Feeds Powered by Dagobah"
feeds:
    - "http://dhrish20.wordpress.com/feed/"
    - "http://lvikneshwar.wordpress.com/feed/"
    - "http://ersanyamkhurana.wordpress.com/feed/"
    - "http://vasi.in/rss.xml"
    - "http://whimsicalputty.wordpress.com/feed/"
    - "http://naiiveuser.blogspot.in/feeds/posts/default"
    - "http://amitt001.github.io/rss.xml"
    - "http://thisisumesh.wordpress.com/feed/"
    - "http://jacksonisaac.wordpress.com/feed/"
    - "http://abhithetechie.wordpress.com/feed/"
    - "http://sudhirkhanger.com/category/linux/feed"
    - "http://dahl007.wordpress.com/feed/"
    - "http://qlixxz.wordpress.com/feed/"
    - "http://papiyasen.wordpress.com/feed/"
    - "http://myopensrc.wordpress.com/feed/"
    - "http://takwas.github.io/meekgeek/feeds/all.atom.xml"
    - "http://nssreedevipillai.blogspot.com/feeds/posts/default"
    - "http://bhargav079.wordpress.com/feed/"
    - "http://nmzaheer.wordpress.com/feed/"
    - "http://ramsandesh.wordpress.com/feed/"
    - "http://vipsyvipul.github.io/feed.xml"
    - "http://athirasnamby.blogspot.in/feeds/posts/default"
    - "http://rahulxarvis.blogspot.in/feeds/posts/default"
    - "http://prashz.wordpress.com/feed/"
    - "http://thejazeto.wordpress.com/feed/"
    - "http://ace139.wordpress.com/feed/"
    - "http://poornimakshirsagar.wordpress.com/feed/"
    - "http://shilpi1993.blogspot.in/feeds/posts/default"
    - "http://rohanroy.com/feed/"
    - "http://papiyasen.wordpress.com/feed/atom/"
    - "http://mayuresh.ghoster.io/rss/"
    - "http://satarupasinha.wordpress.com/feed/"
    - "http://thisisashwanipandey.blogspot.in/feeds/posts/default"
    - "https://mukherjeebidisha94.wordpress.com/feeds/"
    - "http://ishappinessfree.blogspot.com/feeds/posts/default"
    - "http://bnprk27.wordpress.com/feed"
    - "http://nssreedevipillai.blogspot.com/feeds/posts/default"
    - "http://thoughtsbykanika.wordpress.com/feed/"
    - "http://cmmm4.blogspot.in/feeds/posts/default"
    - "http://compsciworld.wordpress.com/feed/"
    - "http://takwas.github.io/meekgeek/feeds/all.atom.xml"
    - "https://Prashantjamkhande.wordpress.com/feed/"
    - "http://anupama13blog.wordpress.com/feed/"
    - "https://amitcsa.wordpress.com/feed/"
    - "https://pabitrapati.wordpress.com/feed/"
    - "https://akhileshdhaundiyal.wordpress.com/feed/"
    - "http://abhishekcs10.blogspot.com/feeds/posts/default"
    - "https://anandprakashtandale.wordpress.com/feed/"
    - "https://meganeshkadam.github.io/post/index.xml"
    - "http://priyankashblog.wordpress.com/feed/"
    - "https://mohammedzee1000.wordpress.com/feed/"
    - "https://technotronsite.wordpress.com/feed/"
    - "http://ankitbanerjee.in/feed/"
    - "https://anupama13blog.wordpress.com/feed/"
    - "https://gobindaakhuli.wordpress.com/feed/"
    - "https://kidandteeninspire.wordpress.com/feed/"
    - "https://alakyadav.wordpress.com/blog/feed/"
    - "https://techandmortals.wordpress.com/feed/"
    - "https://codegeek96.wordpress.com/feed/"
    - "http://inamitk.blogspot.com/feeds/posts/default"
    - "https://medium.com/feed/@lambainsaan"
    - "https://sandeepchoudharyme.wordpress.com/feed/"
    - "https://www.akshayshipurkar.me/blog/feed/"
    - "https://abk14.wordpress.com/feed/"
    - "https://thisisashwanipandey.blogspot.in/feeds/posts/default"
    - "https://coderblog28.wordpress.com/feed/"
    - "https://chirath02.wordpress.com/feed/"
    - "https://dhanvi1.wordpress.com/feed/"
    - "https://geojoyce.wordpress.com/feed/"
    - "https://ksaikiranr.wordpress.com/feed/"
    - "https://amrtanair.wordpress.com/feed/"
    - "https://akshaycv006.wordpress.com/feed/"
    - "https://inamitk.wordpress.com/feed/"
    - "https://rahuldecoded.wordpress.com/feed/"
    - "https://akorep.wordpress.com/feed/"
    - "https://themessier.wordpress.com/feed/"
    - "http://paarttipaa.blogspot.in/feed/posts/default"
    - "http://mr-karan.github.io/feed.xml"
    - "http://ameyjain.wordpress.com/feed/"
    - "http://reserved-bit.com/feed/"
    - "https://jogenderkota.wordpress.com/feed/"
    - "http://marcosalano.me/feed.xml"
    - "http://ruralphysician.blogspot.com/feeds/posts/default/"
    - "https://amankumar119.wordpress.com/blog/feed/"
    - "https://vharshblog.wordpress.com/blog/feed/"
    - "https://ultimatepritam.wordpress.com/feed/"
